# Generated by Django 2.2.2 on 2019-08-09 12:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('entertainment', (('bollywood', 'Bollywoood'), ('hollywod', 'Hollywood'), ('funny', 'Funny'))), ('news', (('politics', 'Politics'), ('science', 'Science'), ('world', 'World'), ('bollywood', 'Bollywoood'), ('other', 'Other'))), ('lifestyle', (('fashion', 'Fashion'), ('food', 'Food'), ('travel', 'Travel'), ('other', 'Other'))), ('gadgets', 'Gadgets'), ('sports', (('cricket', 'Cricket'), ('football', 'Football'), ('other', 'Other')))], default='', max_length=100)),
                ('title', models.CharField(max_length=180)),
                ('tag_line', models.CharField(max_length=255)),
                ('thumbs', models.ImageField(max_length=255, upload_to='thumbs/')),
                ('body', models.TextField()),
                ('advisory', models.TextField(blank=True, null=True)),
                ('disclaimer', models.TextField(blank=True, null=True)),
                ('slug', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
