# Generated by Django 2.2.2 on 2019-08-09 17:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0002_article_keywords'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='by',
            field=models.ForeignKey(default=1, on_delete=models.SET('article desk'), to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.CharField(choices=[('Fun Section', (('funny', 'Funny'), ('bollywood', 'Bollywoood'), ('hollywod', 'Hollywood'), ('entertainment', 'Entertainment'))), ('Info Section', (('politics', 'Politics'), ('science', 'Science'), ('world', 'World'), ('international', 'Inernational'), ('news', 'News'))), ('Lifestyle Section', (('fashion', 'Fashion'), ('food', 'Food'), ('travel', 'Travel'))), ('Sports Section', (('cricket', 'Cricket'), ('football', 'Football'), ('sports', 'Other Sport'))), ('gadgets', 'Gadgets'), ('others', 'Others')], default='', max_length=100),
        ),
    ]
