# Generated by Django 2.2.2 on 2019-08-10 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0005_auto_20190810_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=models.SlugField(help_text='Slug will be generated automatically from the title of the post', max_length=200, unique=True),
        ),
    ]
