# Generated by Django 2.2.2 on 2019-08-11 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0006_auto_20190810_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=models.SlugField(default='--slug--', help_text='Slug will be generated automatically from the title of the post', max_length=200, unique=True),
        ),
    ]
