# Generated by Django 2.2.2 on 2019-08-11 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0007_auto_20190811_2101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=models.SlugField(default='--slug--', help_text='A non editable link will be generated automatically from the title during upload.', max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(help_text='This title is used to make slug for the first time, Slug can not be edited then.', max_length=120),
        ),
    ]
