# Generated by Django 2.2.2 on 2019-08-11 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0008_auto_20190811_2117'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='hide',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.CharField(choices=[('Fun Section', (('funny', 'Funny'), ('bollywood', 'Bollywoood'), ('hollywod', 'Hollywood'), ('entertainment', 'Entertainment'))), ('Info Section', (('politics', 'Politics'), ('science', 'Science'), ('world', 'World'), ('international', 'Inernational'), ('news', 'News'))), ('Lifestyle Section', (('fashion', 'Fashion'), ('food', 'Food'), ('travel', 'Travel'))), ('Sports Section', (('cricket', 'Cricket'), ('football', 'Football'), ('sports', 'Other Sport'))), ('gadgets', 'Gadgets'), ('others', 'Others')], default='', help_text='Category can only be selected once.', max_length=100),
        ),
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=models.SlugField(default='--slug--', help_text='Automatically created from title.', max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(help_text='This title is used to make link for the Article for first time. Link can not be edited then.', max_length=120),
        ),
    ]
