# Generated by Django 2.2.2 on 2019-08-12 08:42

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0010_auto_20190811_2335'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='sub_cat',
            field=models.CharField(choices=[('funny', (('funny', 'Funny'), ('bollywood', 'Bollywoood'), ('hollywod', 'Hollywood'), ('entertainment', 'Entertainment'))), ('Info Section', (('politics', 'Politics'), ('science', 'Science'), ('world', 'World'), ('international', 'Inernational'), ('news', 'News'))), ('Lifestyle Section', (('fashion', 'Fashion'), ('food', 'Food'), ('travel', 'Travel'))), ('Sports Section', (('cricket', 'Cricket'), ('football', 'Football'), ('sports', 'Other Sport'))), ('gadgets', 'Gadgets'), ('others', 'Others')], default='', help_text='Sub category can only be selected only once.', max_length=100),
        ),
        migrations.AlterField(
            model_name='article',
            name='advisory',
            field=models.TextField(blank=True, help_text='This is a light weight text for readers to be advised about. ( Optional )', null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='body',
            field=ckeditor_uploader.fields.RichTextUploadingField(help_text='Article body'),
        ),
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.CharField(choices=[('funny', 'Funny')], default='', help_text='Category can only be selected only once.', max_length=100),
        ),
        migrations.AlterField(
            model_name='article',
            name='disclaimer',
            field=models.TextField(blank=True, help_text='This is a light weight text for readers descretion. ( Optional )', null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='is_live',
            field=models.BooleanField(default=1, help_text='If ticked, it means this Article is running live.'),
        ),
        migrations.AlterField(
            model_name='article',
            name='keywords',
            field=models.TextField(help_text='Use relevent keywords and key phrases. ( eg - jArticle, articles on jArticle, funny article )'),
        ),
        migrations.AlterField(
            model_name='article',
            name='tag_line',
            field=models.CharField(help_text='Catchy phrase followed by title. Also used as social description for content.', max_length=255),
        ),
        migrations.AlterField(
            model_name='article',
            name='thumbs',
            field=models.ImageField(help_text='Thumbnail and featured image of the article. Use ratio as w:h 2:1 with high resolution image. Try to keep the image less than 1MB in size for fast loading.', max_length=255, upload_to='thumbs/'),
        ),
    ]
