# Generated by Django 2.2.2 on 2019-08-12 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0012_auto_20190812_1446'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='is_live',
            new_name='is_published',
        ),
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.CharField(choices=[('a', [('draft', 'draft'), ('draft', 'draft')]), ('b', [('published', 'published'), ('published', 'published')])], default='', help_text='Category can only be selected only once.', max_length=100),
        ),
    ]
