# Generated by Django 2.2.2 on 2019-08-12 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0013_auto_20190812_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.CharField(default='explore', help_text='Category depends on label', max_length=100),
        ),
    ]
