# Generated by Django 2.2.2 on 2019-08-12 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0014_auto_20190812_1734'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='sub_cat',
        ),
        migrations.AddField(
            model_name='article',
            name='label',
            field=models.CharField(choices=[('Entertainment', (('bollywood', 'Bollywood'), ('hollywood', 'Hollywood'), ('funny', 'Funny'))), ('News', (('politics', 'Politics'), ('science', 'Science'), ('world', 'World'))), ('Sports', (('cricket', 'Cricket'), ('football', 'Football'), ('games', 'Games'))), ('Lifestyle', (('fashion', 'Fashion'), ('food', 'Food'), ('travel', 'Travel'))), ('Gadgets', (('mobile', 'Mobile'), ('pc', 'PC'), ('latest', 'Latest'), ('technology', 'Technology'), ('inventions', 'Inventions'))), ('Explore', (('top10', 'Top 10'), ('others', 'other')))], default='', help_text='Sub category can only be selected only once.', max_length=100),
        ),
    ]
