# Generated by Django 2.2.2 on 2019-08-12 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0015_auto_20190812_1815'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='tags',
            field=models.TextField(blank=True, help_text='This is a light weight text for readers to be advised about. ( Optional )', null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.CharField(default='explore', help_text='Category depends on label. Default is explore, It will change as per the label.', max_length=100),
        ),
        migrations.AlterField(
            model_name='article',
            name='label',
            field=models.CharField(choices=[('Entertainment', (('bollywood', 'Bollywood'), ('hollywood', 'Hollywood'), ('funny', 'Funny'))), ('News', (('politics', 'Politics'), ('science', 'Science'), ('world', 'World'))), ('Sports', (('cricket', 'Cricket'), ('football', 'Football'), ('games', 'Games'))), ('Lifestyle', (('fashion', 'Fashion'), ('food', 'Food'), ('travel', 'Travel'))), ('Gadgets', (('mobile', 'Mobile'), ('pc', 'PC'), ('latest', 'Latest'), ('technology', 'Technology'), ('inventions', 'Inventions'))), ('Explore', (('top10', 'Top 10'), ('others', 'other')))], default='explore', help_text='Sub category can only be selected only once.', max_length=100),
        ),
    ]
