# Generated by Django 2.2.2 on 2019-08-13 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0016_auto_20190812_1911'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='page_view',
            field=models.PositiveIntegerField(default=0, help_text='How many times the page rendered.'),
        ),
        migrations.AlterField(
            model_name='article',
            name='label',
            field=models.CharField(choices=[('Entertainment', (('funny', 'Funny'), ('bollywood', 'Bollywood'), ('hollywood', 'Hollywood'), ('tvseries', 'Tv Series'), ('reviews', 'Reviews'))), ('News', (('politics', 'Politics'), ('science', 'Science'), ('world', 'World'))), ('Sports', (('cricket', 'Cricket'), ('football', 'Football'), ('games', 'Games'))), ('Lifestyle', (('fashion', 'Fashion'), ('food', 'Food'), ('travel', 'Travel'))), ('Gadgets', (('mobile', 'Mobile'), ('pc', 'PC'), ('latest', 'Latest'), ('technology', 'Technology'), ('inventions', 'Inventions'))), ('Explore', (('top10', 'Top 10'), ('others', 'other')))], default='explore', help_text='Sub category can only be selected only once.', max_length=100),
        ),
    ]
