# Generated by Django 2.2.2 on 2020-01-01 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0017_auto_20190813_2024'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='affiliate_code',
            field=models.CharField(default='NONE', help_text='Affiliate Code, Please Refer To Code Sheet', max_length=50),
        ),
    ]
