# Generated by Django 2.2.2 on 2020-08-09 10:01

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('uploads', '0019_editor'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Editor',
            new_name='Content',
        ),
    ]
