# Generated by Django 2.2.2 on 2020-08-12 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0020_auto_20200809_1531'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='is_editable',
            field=models.BooleanField(default=1, help_text='If ticked, it means this Article is editable.'),
        ),
        migrations.AddField(
            model_name='content',
            name='is_new',
            field=models.BooleanField(default=1, help_text='If ticked, it means the article is new.'),
        ),
        migrations.AddField(
            model_name='content',
            name='is_rejected',
            field=models.BooleanField(default=1, help_text='If ticked, it means this Article is rejected.'),
        ),
    ]
