# Generated by Django 2.2.2 on 2020-08-21 17:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0021_auto_20200812_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='by',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.SET('article desk'), to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='content',
            name='page_view',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='How many times the page rendered.', null=True),
        ),
        migrations.AlterField(
            model_name='content',
            name='slug',
            field=models.SlugField(blank=True, default='--slug--', help_text='Automatically created from title.', max_length=200, null=True, unique=True),
        ),
    ]
