# Generated by Django 2.2.2 on 2020-09-02 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0026_auto_20200902_2225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='label',
            field=models.CharField(blank=True, choices=[('Entertainment', (('funny', 'Funny'), ('bollywood', 'Bollywood'), ('hollywood', 'Hollywood'), ('tvseries', 'Tv Series'), ('reviews', 'Reviews'))), ('News', (('politics', 'Politics'), ('science', 'Science'), ('world', 'World'))), ('Sports', (('cricket', 'Cricket'), ('football', 'Football'), ('games', 'Games'))), ('Lifestyle', (('fashion', 'Fashion'), ('food', 'Food'), ('travel', 'Travel'))), ('Gadgets', (('mobile', 'Mobile'), ('pc', 'PC'), ('latest', 'Latest'), ('technology', 'Technology'), ('inventions', 'Inventions'))), ('Explore', (('top10', 'Top 10'), ('others', 'other')))], default='other', help_text='Sub category can only be selected only once.', max_length=100, null=True),
        ),
    ]
