# Generated by Django 2.2.2 on 2020-09-12 10:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0027_auto_20200902_2302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='by',
            field=models.ForeignKey(blank=True, default='1', null=True, on_delete=models.SET('article desk'), to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='content',
            name='is_editable',
            field=models.BooleanField(blank=True, default=1, help_text='If ticked, it means this Article is editable.', null=True),
        ),
        migrations.AlterField(
            model_name='content',
            name='is_new',
            field=models.BooleanField(blank=True, default=1, help_text='If ticked, it means the article is new.', null=True),
        ),
        migrations.AlterField(
            model_name='content',
            name='is_rejected',
            field=models.BooleanField(blank=True, default=1, help_text='If ticked, it means this Article is rejected.', null=True),
        ),
        migrations.AlterField(
            model_name='content',
            name='is_updated',
            field=models.BooleanField(blank=True, default=1, help_text='If ticked, it means this Article is running live.', null=True),
        ),
        migrations.AlterField(
            model_name='content',
            name='label',
            field=models.CharField(blank=True, choices=[('Entertainment', (('funny', 'Funny'), ('bollywood', 'Bollywood'), ('hollywood', 'Hollywood'), ('tvseries', 'Tv Series'), ('reviews', 'Reviews'))), ('News', (('politics', 'Politics'), ('science', 'Science'), ('world', 'World'))), ('Sports', (('cricket', 'Cricket'), ('football', 'Football'), ('games', 'Games'))), ('Lifestyle', (('fashion', 'Fashion'), ('food', 'Food'), ('travel', 'Travel'))), ('Gadgets', (('mobile', 'Mobile'), ('pc', 'PC'), ('latest', 'Latest'), ('technology', 'Technology'), ('inventions', 'Inventions'))), ('Explore', (('top10', 'Top 10'), ('others', 'other')))], default='others', help_text="Sub category can only be selected only once. Deafualt is 'other'", max_length=100, null=True),
        ),
    ]
